id: I35CFDCD5
legacy_id: P000402
ocr_import_info:
  bdrc_scan_id: W28799
  source: bdrc
  ocr_info:
    timestamp: '2020-03-17T22:55:25'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T10:19:37.433428+00:00'
last_modified: 2022-08-27 18:20:13.831650
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W28799
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW28799
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དྲང་ངེས་རྣམ་འབྱེད་ཀྱི་དགོངས་པའི་དོན་གསལ་བར་བྱེད་པའི་མེ་ལོང་།
  author: བྲ་ཏི་དགེ་བཤེས་ཆུང་བ་བློ་བཟང་དགེ་ལེགས།
statistics:
  ocr_word_mean_confidence_index: 0.9326669862756208
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1KG18157:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG18157
      total_pages: 436
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG18157.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9326669862756208
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
